version: "2.0"
services:

  development:
    build:
      context: ./
      dockerfile: "development.dockerfile"
    command: "sh -c 'while true; do sleep 1; done'"
    volumes:
      - ..:/development


  build:
    build:
      context: ./
      dockerfile: "development.dockerfile"
    command: "sh -c 'while true; do sleep 1; done'"
