version: "2.0"
services:

  development:
    build:
      context: ./
      dockerfile: "development.dockerfile"
    command: "sh -c 'while true; do sleep 1; done'"
    volumes:
      - ..:/development


  build:
    build:
      context: ./
      dockerfile: "development.dockerfile"
    command: |
      sh -c "
        ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa && \
        ssh-keygen -f /etc/ssh/ssh_host_dsa_key -N '' -t dsa && \
        /usr/sbin/sshd -D
      "
