version: "2.0"
services:

  development:
    build:
      context: ./
      dockerfile: "development.dockerfile"
    command: "sh -c 'while true; do sleep 1; done'"
    working_dir: /development/testapp
    volumes:
      - ..:/development
      - ../../edeliver:/edeliver


  build:
    build:
      context: ./
      dockerfile: "development.dockerfile"
    command: /usr/sbin/sshd -D
    volumes:
      - ../../edeliver:/edeliver


  staging:
    build:
      context: ./
      dockerfile: "development.dockerfile"
    command: /usr/sbin/sshd -D
    working_dir: /root/testapp
